esphome:
  name: m5-chain-dualkey
  friendly_name: M5 Chain Dualkey

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf

# Enable logging
logger:
  
# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  - platform: esphome
    password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5-Chain-Dualkey"
    password: "..."

captive_portal:


binary_sensor:
  # -----------------------
  # BUTTONS (G0 & G17) – swapped
  # -----------------------
  - platform: gpio
    id: key1
    name: "DualKey Button 2"
    pin:
      number: 0
      mode: INPUT
      inverted: true

  - platform: gpio
    id: key2
    name: "DualKey Button 1"
    pin:
      number: 17
      mode: INPUT
      inverted: true

  # -----------------------
  # Derived binary sensors
  # -----------------------
  - platform: template
    name: "DualKey USB Plugged In"
    id: usb_power
    device_class: power
    lambda: |-
      return id(adc_vbus).state > 0.5;  // adjust threshold if needed

  - platform: template
    name: "DualKey Charging"
    id: charging
    device_class: battery_charging
    lambda: |-
      const float v = id(adc_charge).state;  // this must be the "DualKey Charge Status" sensor
      return v < 2.4;  // threshold between 1.65 V and 3.15 V

sensor:
  # Raw battery voltage (read from ADC on G10)
  - platform: adc
    id: adc_battery
    pin: 10
    name: "DualKey Battery Voltage"
    attenuation: 12db
    update_interval: 30s
    filters:
      - multiply: 1.5018

  # Battery %
  - platform: template
    id: battery_percent
    name: "DualKey Battery Level"
    unit_of_measurement: "%"
    icon: "mdi:battery"
    update_interval: 30s
    lambda: |-
      if (id(adc_battery).state <= 3.10) return 0;
      if (id(adc_battery).state >= 4.20) return 100;
      return (id(adc_battery).state - 3.10) * 100.0 / (4.20 - 3.10);

  # USB 5V presence
  - platform: adc
    id: adc_vbus
    pin: 2
    name: "DualKey USB VBUS"
    attenuation: 12db
    update_interval: 10s

  # Charge state ADC
  - platform: adc
    id: adc_charge
    pin: 9
    name: "DualKey Charge Status"
    attenuation: 12db
    update_interval: 10s

  # DIP switches
  - platform: adc
    id: switch_1_adc
    pin: 8
    name: "DIP Switch 1"
    attenuation: 12db
    update_interval: 1s

  - platform: adc
    id: switch_2_adc
    pin: 7
    name: "DIP Switch 2"
    attenuation: 12db
    update_interval: 1s

switch:
  - platform: gpio
    id: led_power_switch
    pin: 40   # KBD_WS2812_POWER_IO - LED power control

light:
  - platform: esp32_rmt_led_strip
    id: dualkey_leds
    internal: true
    rgb_order: GRB       # LED_PIXEL_FORMAT_GRB from esp_duo.c
    chipset: WS2812 # LED_MODEL_WS2812 from esp_duo.c
    pin: 21         # KBD_WS2812_GPIO
    num_leds: 2     # LIGHTMAP_NUM from lightmap.h
    # Power supply dependency
    on_turn_on:
      - switch.turn_on: led_power_switch
    on_turn_off:
      - switch.turn_off: led_power_switch

  - platform: partition
    id: dualkey_led_1
    name: "DualKey LED 1"
    segments:
      - id: dualkey_leds
        from: 0
        to: 0

  - platform: partition
    id: dualkey_led_2
    name: "DualKey LED 2"
    segments:
      - id: dualkey_leds
        from: 1
        to: 1

